
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gngndqstipgvymkdlllg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduZ25kcXN0aXBndnlta2RsbGxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzM3ODMsImV4cCI6MjA2NTc0OTc4M30.OM7wW8vc_Mswt4FAX-CQ5707e_TnApc0pM2iDncsyls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: false, // Changed to false since we're using Privy for auth
    autoRefreshToken: false,
  }
});

// Function to set the auth token from Privy
export const setSupabaseAuth = (token: string) => {
  supabase.auth.setSession({
    access_token: token,
    refresh_token: '',
    expires_in: 3600,
    expires_at: Math.floor(Date.now() / 1000) + 3600,
    token_type: 'bearer',
    user: null
  });
};
